"""init

Revision ID: 4ab513d78e9f
Revises: 
Create Date: 2025-05-13 12:59:23.720017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab513d78e9f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kategori'))
    )
    op.create_index(op.f('ix_kategori_nama'), 'kategori', ['nama'], unique=True)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('artikel',
    sa.Column('judul', sa.String(length=100), nullable=False),
    sa.Column('konten', sa.Text(), nullable=False),
    sa.Column('penulis', sa.String(length=100), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_publikasi', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], name=op.f('fk_artikel_kategori_id_kategori')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artikel'))
    )
    op.create_index(op.f('ix_artikel_judul'), 'artikel', ['judul'], unique=False)
    op.create_index(op.f('ix_artikel_penulis'), 'artikel', ['penulis'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artikel_penulis'), table_name='artikel')
    op.drop_index(op.f('ix_artikel_judul'), table_name='artikel')
    op.drop_table('artikel')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index('my_index', table_name='models', mysql_length=255)
    op.drop_table('models')
    op.drop_index(op.f('ix_kategori_nama'), table_name='kategori')
    op.drop_table('kategori')
    # ### end Alembic commands ###
